# Generated by Django 4.2.3 on 2024-06-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('Apple', 'Apple'), ('Dell', 'Dell'), ('HP', 'HP'), ('Lenovo', 'Lenovo'), ('Asus', 'Asus'), ('Acer', 'Acer'), ('Microsoft', 'Microsoft'), ('Samsung', 'Samsung'), ('MSI', 'MSI')], max_length=50)),
                ('year_of_release', models.IntegerField()),
                ('ram_size', models.PositiveIntegerField(help_text='RAM size in GB')),
                ('hdd_size', models.PositiveIntegerField(help_text='HDD size in GB')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.PositiveIntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
