# Generated by Django 4.2.3 on 2024-06-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_laptop'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PUBLISHED', 'Опубликован'), ('UNPUBLISHED', 'Не опубликован'), ('BANNED', 'Забанен')], default='UNPUBLISHED', max_length=20)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('publication_date', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(choices=[('TECHNOLOGY', 'Технологии'), ('HEALTH', 'Здоровье'), ('EDUCATION', 'Образование'), ('ENTERTAINMENT', 'Развлечения'), ('TRAVEL', 'Путешествия')], default='TECHNOLOGY', max_length=20)),
            ],
        ),
    ]
